# Generated by Django 5.0.2 on 2024-02-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_jain'),
    ]

    operations = [
        migrations.CreateModel(
            name='sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('category', models.IntegerField(choices=[(1, 'cafe'), (2, 'club'), (3, 'Restaurant')])),
                ('rating', models.FloatField()),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
