# Generated by Django 5.0.2 on 2024-02-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
