# Generated by Django 5.0.2 on 2024-02-13 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0008_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='bar',
            field=models.ForeignKey(db_column='rid', default=1, on_delete=django.db.models.deletion.CASCADE, to='cafeteria.bar'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='jain',
            field=models.ForeignKey(db_column='jid', default=1, on_delete=django.db.models.deletion.CASCADE, to='cafeteria.jain'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='place',
            field=models.ForeignKey(db_column='pid', default=1, on_delete=django.db.models.deletion.CASCADE, to='cafeteria.place'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='sweet',
            field=models.ForeignKey(db_column='did', default=1, on_delete=django.db.models.deletion.CASCADE, to='cafeteria.sweet'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='cid',
            field=models.ForeignKey(db_column='cid', default=1, on_delete=django.db.models.deletion.CASCADE, to='cafeteria.cafes'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
